package com.ayustark.todo_manager.db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey


//annotate with @Entity to treat it as entity class
//If table name not given it give the same name as that of class here "Note"
@Entity(tableName = "Notes_Data_Table")
data class Note(
    //Making the ID primary key and autogenerated for each value
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "Note_Id")
    //Column name is given to avoid confusion which may happen when size of app increases
    var id: Int,

    @ColumnInfo(name = "Note_Title")
    var title: String, //var so that we can update it later

    @ColumnInfo(name = "Note_Description")
    var description: String,

    @ColumnInfo(name = "Note_DueDate")
    var date: String
)